BASE_DIR = "adaptive_analytics"
DBT_PROJECT_PATH = "adaptive_analytics/dbt_project"
DB_FILE = "adaptive_analytics/dbt_project/sample_superstore.db"
DBT_PROFILES_PATH = "adaptive_analytics/dbt_project"
USER_ID = "e97435c1-f401-40da-aef7-623ded555656"